In [2]:
import pandas as pd
import os
from dotenv import load_dotenv
import sqlalchemy
import psycopg2

### Loading datasets

In [28]:
from dotenv import load_dotenv
import os

load_dotenv()

data_path = os.getenv('DATA_PATH')

In [29]:
movies = pd.read_csv(f'{data_path}/movie.csv')
ratings = pd.read_csv(f'{data_path}/rating.csv')

#### Quick overview of the data

In [30]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 27278 entries, 0 to 27277
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  27278 non-null  int64
 1   title    27278 non-null  str
 2   genres   27278 non-null  str
dtypes: int64(1), str(2)
memory usage: 639.5 KB

In [31]:
ratings.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000263 entries, 0 to 20000262
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   userId     int64
 1   movieId    int64
 2   rating     float64
 3   timestamp  str
dtypes: float64(1), int64(2), str(1)
memory usage: 610.4 MB

In [32]:
movies.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [33]:
ratings.head()

   userId  movieId  rating            timestamp
0       1        2     3.5  2005-04-02 23:53:47
1       1       29     3.5  2005-04-02 23:31:16
2       1       32     3.5  2005-04-02 23:33:39
3       1       47     3.5  2005-04-02 23:32:07
4       1       50     3.5  2005-04-02 23:29:40

#### Check for missing values in both datasets

In [34]:
movies.isnull().sum()
ratings.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

#### Convert 'timestamp' from Unix format to readable DateTime

In [35]:
ratings['timestamp'] = pd.to_datetime(ratings['timestamp'])

In [36]:
ratings['timestamp'].dtype

dtype('<M8[us]')

#### Extract 'year' from 'title' using Regex and create a new column

In [37]:
movies['year'] = movies['title'].str.extract(r'\((\d{4})\)')

In [38]:
movies.columns

Index(['movieId', 'title', 'genres', 'year'], dtype='str')

#### Remove the year from the 'title' string for a cleaner look

In [39]:
movies['title'] = movies['title'].str.replace(r'\s\(\d{4}\)', '', regex=True)

In [40]:
movies.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

##### Genres column was split by `|` delimiter and exploded into separate rows to create a normalized `movies_genres` table, enabling efficient SQL queries by genre.

In [41]:
movies_genres = movies[['movieId', 'genres']].copy()
movies_genres['genres'] = movies_genres['genres'].str.split('|')
movies_genres = movies_genres.explode('genres')

In [44]:
movies_genres.head()

   movieId     genres
0        1  Adventure
0        1  Animation
0        1   Children
0        1     Comedy
0        1    Fantasy

#### Control the dataframes for duplicated values

In [ ]:
movies.duplicated().sum()

np.int64(0)

In [49]:
ratings.duplicated().sum()

np.int64(0)

In [50]:
movies_genres.duplicated().sum()

np.int64(0)

## Data is ready for SQL

#### Using dotenv for secuirty and connect to postgresql

In [47]:
from sqlalchemy import create_engine

engine = create_engine(f"postgresql://{os.getenv('DB_USER')}:{os.getenv('DB_PASSWORD')}@localhost:5432/{os.getenv('DB_NAME')}")
print('Connected!')

Connected!

#### Sending dataframes to psql as tables

In [48]:
movies.to_sql('movies', engine, if_exists='replace', index=False)
movies_genres.to_sql('movies_genres', engine, if_exists='replace', index=False)
ratings.to_sql('ratings', engine, if_exists='replace',chunksize=10000 ,index=False)
print('Tables were created')

Tables were created